import React, { useMemo } from 'react';
import { useApp } from '../context/AppContext';
import { useLanguage } from '../context/LanguageContext';
import { generateReportData, BUSINESS_TYPES } from '../data/datasets';
import Speaker from '../components/Speaker';
import MapComponent from '../components/MapComponent';
import { getCityData } from '../data/cityData';

export default function ReportPage() {
  const { userData, setScreen } = useApp();
  const { t } = useLanguage();
  const report = useMemo(() => generateReportData(userData.businessType), [userData.businessType]);
  const businessLabel = BUSINESS_TYPES.find(b => b.value === userData.businessType)?.label || userData.businessType;

  const handleDownload = () => {
    const reportText = `
GRAMSAHAY - BUSINESS FEASIBILITY REPORT
========================================

Business: ${businessLabel}
Entrepreneur: ${userData.name}
Address: ${userData.address}
Location: ${userData.village}, ${userData.district}, ${userData.state}
Community: ${userData.community.toUpperCase()}

MODULE 1: MARKET REACH
----------------------
Population in 10km radius: ${report.marketReach.population.toLocaleString()}
Households: ${report.marketReach.households.toLocaleString()}
Target customers: ${report.marketReach.targetCustomers.toLocaleString()} families
Distribution channels: ${report.marketReach.channels.join(', ')}

MODULE 2: OPPORTUNITY ANALYSIS
-------------------------------
${report.opportunity.map(o => `• ${o}`).join('\n')}

MODULE 3: SWOT ANALYSIS
------------------------
STRENGTHS:
${report.swot.strengths.map(s => `• ${s}`).join('\n')}

WEAKNESSES:
${report.swot.weaknesses.map(w => `• ${w}`).join('\n')}

OPPORTUNITIES:
${report.swot.opportunities.map(o => `• ${o}`).join('\n')}

THREATS:
${report.swot.threats.map(t => `• ${t}`).join('\n')}

MODULE 4: THREAT IDENTIFICATION
--------------------------------
${report.threats.map(t => `• ${t.name} (${t.severity}): ${t.description}`).join('\n')}

MODULE 5: COMPETITOR MAPPING
------------------------------
${report.competitors.map(c => `• ${c.name} - ${c.distance} away, Rating: ${c.rating}`).join('\n')}

MODULE 6: PRODUCT MARKET VALUE
-------------------------------
Suggested pricing: ${report.pricing.suggested}

Pricing tips:
${report.pricing.tips.map(t => `• ${t}`).join('\n')}

---
Generated by GramSahay AI
Ministry of Social Justice & Empowerment
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `GramSahay_Report_${userData.name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-8">
      <header className="bg-white shadow-sm border-b sticky top-0 z-40">
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-green-700 rounded-lg flex items-center justify-center text-white text-lg font-bold">ग्रा</div>
            <div>
              <h1 className="text-lg font-bold text-gray-800">{t.businessReport}</h1>
              <p className="text-xs text-gray-500">{userData.name} • {userData.village}, {userData.district}</p>
            </div>
          </div>
          <button onClick={() => setScreen('financial-plan')} className="text-gray-500 hover:text-gray-700 text-sm px-3 py-1.5 rounded-lg hover:bg-gray-100">
            ← {t.back}
          </button>
        </div>
      </header>

      <div className="max-w-5xl mx-auto px-4 py-6">
        <div className="mb-6">
          <Speaker text={`${t.businessReport} for ${businessLabel}. This report covers market reach, opportunity analysis, SWOT analysis, threat identification, competitor mapping, and product market value.`} />
        </div>

        <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="text-2xl">🎯</span> 1. {t.marketReach || 'Market Reach'}
          </h3>
          <div className="bg-blue-50 rounded-lg p-4 border border-blue-100 mb-4">
            <div className="grid grid-cols-3 gap-4 text-center">
              <div>
                <p className="text-2xl font-bold text-gray-800">{report.marketReach.population.toLocaleString()}</p>
                <p className="text-xs text-gray-600">Population (10km)</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-800">{report.marketReach.households.toLocaleString()}</p>
                <p className="text-xs text-gray-600">Households</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-800">{report.marketReach.targetCustomers.toLocaleString()}</p>
                <p className="text-xs text-gray-600">Target Customers</p>
              </div>
            </div>
          </div>
          <div>
            <p className="font-semibold text-gray-700 mb-2">Distribution Channels:</p>
            <div className="flex flex-wrap gap-2">
              {report.marketReach.channels.map((ch, i) => (
                <span key={i} className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium">{ch}</span>
              ))}
            </div>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="text-2xl">💡</span> 2. {t.opportunityAnalysis || 'Opportunity Analysis'}
          </h3>
          <div className="bg-green-50 rounded-lg p-4 border border-green-100">
            <ul className="space-y-2">
              {report.opportunity.map((opp, i) => (
                <li key={i} className="flex items-start gap-2 text-gray-700">
                  <span className="text-green-600 mt-0.5">✅</span>
                  <span>{opp}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="text-2xl">📋</span> 3. {t.swotAnalysis || 'SWOT Analysis'}
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-green-50 rounded-xl p-4 border-2 border-green-200">
              <h4 className="font-bold text-green-800 mb-3">💪 Strengths</h4>
              <ul className="space-y-2">
                {report.swot.strengths.map((s, i) => (
                  <li key={i} className="flex items-start gap-2 text-green-900 text-sm">
                    <span className="text-green-600">●</span><span>{s}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-orange-50 rounded-xl p-4 border-2 border-orange-200">
              <h4 className="font-bold text-orange-800 mb-3">⚡ Weaknesses</h4>
              <ul className="space-y-2">
                {report.swot.weaknesses.map((w, i) => (
                  <li key={i} className="flex items-start gap-2 text-orange-900 text-sm">
                    <span className="text-orange-600">●</span><span>{w}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-blue-50 rounded-xl p-4 border-2 border-blue-200">
              <h4 className="font-bold text-blue-800 mb-3">🌟 Opportunities</h4>
              <ul className="space-y-2">
                {report.swot.opportunities.map((o, i) => (
                  <li key={i} className="flex items-start gap-2 text-blue-900 text-sm">
                    <span className="text-blue-600">●</span><span>{o}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-red-50 rounded-xl p-4 border-2 border-red-200">
              <h4 className="font-bold text-red-800 mb-3">⚠️ Threats</h4>
              <ul className="space-y-2">
                {report.swot.threats.map((t, i) => (
                  <li key={i} className="flex items-start gap-2 text-red-900 text-sm">
                    <span className="text-red-600">●</span><span>{t}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="text-2xl">⚠️</span> 4. {t.threatIdentification || 'Threat Identification'}
          </h3>
          <div className="space-y-3">
            {report.threats.map((t, i) => (
              <div key={i} className={`rounded-lg p-4 border-2 ${t.severity === 'high' ? 'bg-red-50 border-red-200' : t.severity === 'medium' ? 'bg-yellow-50 border-yellow-200' : 'bg-gray-50 border-gray-200'}`}>
                <div className="flex items-center justify-between mb-1">
                  <span className="font-bold text-gray-800">{t.name}</span>
                  <span className={`text-xs px-2 py-1 rounded-full font-semibold ${t.severity === 'high' ? 'bg-red-200 text-red-800' : t.severity === 'medium' ? 'bg-yellow-200 text-yellow-800' : 'bg-gray-200 text-gray-800'}`}>
                    {t.severity.toUpperCase()}
                  </span>
                </div>
                <p className="text-sm text-gray-600">{t.description}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="text-2xl">🏪</span> 5. {t.competitorMapping || 'Competitor Mapping'}
          </h3>
          <div className="overflow-x-auto mb-6">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50">
                  <th className="text-left p-3 font-semibold text-gray-700">Business</th>
                  <th className="text-left p-3 font-semibold text-gray-700">Distance</th>
                  <th className="text-left p-3 font-semibold text-gray-700">Rating</th>
                </tr>
              </thead>
              <tbody>
                {report.competitors.map((c, i) => (
                  <tr key={i} className="border-t border-gray-100">
                    <td className="p-3 text-gray-800">{c.name}</td>
                    <td className="p-3 text-gray-600">{c.distance}</td>
                    <td className="p-3 text-gray-600">⭐ {c.rating}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          
          {/* Map showing competitor locations */}
          {userData.village && userData.district && userData.state && (() => {
            // Try to get coordinates from city data
            const cityData = getCityData(userData.district) || getCityData(userData.village);
            const defaultCoords = cityData ? cityData.coordinates : { lat: 11.0168, lng: 76.9558 };
            
            return (
              <div className="mt-6">
                <h4 className="text-lg font-semibold text-gray-800 mb-3 flex items-center gap-2">
                  <span>🗺️</span> Competitor Locations on Map
                </h4>
                <MapComponent
                  height="400px"
                  zoom={13}
                  showBanks={false}
                  showMarkets={false}
                  userLocation={{
                    lat: defaultCoords.lat,
                    lng: defaultCoords.lng,
                    address: `${userData.village}, ${userData.district}, ${userData.state}`
                  }}
                  competitors={report.competitors}
                />
                <p className="text-xs text-gray-500 mt-2 text-center">
                  Map shows your location and nearby competitors
                </p>
              </div>
            );
          })()}
        </div>

        <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="text-2xl">💲</span> 6. {t.productMarketValue || 'Product Market Value'}
          </h3>
          <div className="bg-indigo-50 rounded-lg p-4 border border-indigo-100 mb-4">
            <p className="font-semibold text-gray-800 mb-2">Suggested Pricing:</p>
            <p className="text-gray-700">{report.pricing.suggested}</p>
          </div>
          <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
            <p className="font-semibold text-gray-800 mb-2">💡 Pricing Tips:</p>
            <ul className="space-y-1 text-sm text-gray-600">
              {report.pricing.tips.map((tip, i) => (
                <li key={i}>• {tip}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Business Statistics */}
        {report.statistics && (
          <div className="bg-white rounded-2xl shadow-md p-6 mb-6 border border-gray-100">
            <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
              <span className="text-2xl">📊</span> Business Statistics
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                <p className="text-xs text-gray-600 mb-1">3-Year Survival Rate</p>
                <p className="text-2xl font-bold text-green-700">{report.statistics.survivalRate}%</p>
              </div>
              <div className="bg-blue-50 rounded-lg p-4 border border-blue-200">
                <p className="text-xs text-gray-600 mb-1">Avg Monthly Revenue</p>
                <p className="text-2xl font-bold text-blue-700">₹{report.statistics.avgRevenue.toLocaleString('en-IN')}</p>
              </div>
              <div className="bg-purple-50 rounded-lg p-4 border border-purple-200">
                <p className="text-xs text-gray-600 mb-1">Profit Margin</p>
                <p className="text-2xl font-bold text-purple-700">{report.statistics.profitMargin}%</p>
              </div>
              <div className="bg-orange-50 rounded-lg p-4 border border-orange-200">
                <p className="text-xs text-gray-600 mb-1">Setup Time</p>
                <p className="text-2xl font-bold text-orange-700">{report.statistics.setupTime}</p>
              </div>
            </div>
            <p className="text-xs text-gray-500 mt-4 italic">Source: {report.statistics.source}</p>
          </div>
        )}

        <div className="bg-gradient-to-r from-green-600 to-green-700 rounded-2xl shadow-lg p-6 text-center text-white">
          <h3 className="text-xl font-bold mb-2">{t.download || 'Download Your Report'}</h3>
          <p className="text-green-100 mb-4">Save this report for your records</p>
          <button
            onClick={handleDownload}
            className="bg-white text-green-700 px-8 py-3 rounded-xl font-bold text-lg hover:bg-green-50 transition-all shadow-md"
          >
            📥 {t.download || 'Download Report'}
          </button>
        </div>
      </div>
    </div>
  );
}
